import { db } from '@/db';
import { pets } from '@/db/schema';

async function main() {
    const samplePets = [
        {
            userId: 'user_1',
            name: 'Buddy',
            species: 'dog',
            breed: 'Golden Retriever',
            age: 3,
            notes: 'Very social, loves meeting new people and needs daily walks',
            imageUrl: 'https://example.com/pet-photos/buddy-golden-retriever.jpg',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 'user_1',
            name: 'Whiskers',
            species: 'cat',
            breed: 'Persian',
            age: 5,
            notes: 'Prefers quiet spaces and gentle handling, needs daily brushing',
            imageUrl: 'https://example.com/pet-photos/whiskers-persian.jpg',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 'user_1',
            name: 'Charlie',
            species: 'bird',
            breed: 'Cockatiel',
            age: 2,
            notes: 'Very talkative and social, loves whistling along to music',
            imageUrl: 'https://example.com/pet-photos/charlie-cockatiel.jpg',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 'user_1',
            name: 'Nemo',
            species: 'fish',
            breed: 'Betta',
            age: 1,
            notes: 'Feed tropical fish flakes twice daily, keep water temperature at 78°F',
            imageUrl: 'https://example.com/pet-photos/nemo-betta.jpg',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            userId: 'user_2',
            name: 'Max',
            species: 'dog',
            breed: 'German Shepherd',
            age: 7,
            notes: 'Medication for arthritis, given with evening meal. Very loyal and protective',
            imageUrl: 'https://example.com/pet-photos/max-german-shepherd.jpg',
            createdAt: new Date('2023-11-05').toISOString(),
            updatedAt: new Date('2023-11-05').toISOString(),
        },
        {
            userId: 'user_2',
            name: 'Luna',
            species: 'cat',
            breed: 'Maine Coon',
            age: 4,
            notes: 'Large and gentle, loves to play with feather toys in the evening',
            imageUrl: 'https://example.com/pet-photos/luna-maine-coon.jpg',
            createdAt: new Date('2023-12-12').toISOString(),
            updatedAt: new Date('2023-12-12').toISOString(),
        },
        {
            userId: 'user_2',
            name: 'Spike',
            species: 'reptile',
            breed: 'Bearded Dragon',
            age: 3,
            notes: 'Requires UV lighting and basking spots, feed leafy greens and crickets',
            imageUrl: 'https://example.com/pet-photos/spike-bearded-dragon.jpg',
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            userId: 'user_2',
            name: 'Goldie',
            species: 'fish',
            breed: 'Goldfish',
            age: null,
            notes: 'Part of community tank, very peaceful with other fish',
            imageUrl: 'https://example.com/pet-photos/goldie-goldfish.jpg',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 'user_3',
            name: 'Bella',
            species: 'dog',
            breed: 'French Bulldog',
            age: 2,
            notes: 'Rescue pet, still adjusting to new home. Needs patience and gentle training',
            imageUrl: 'https://example.com/pet-photos/bella-french-bulldog.jpg',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            userId: 'user_3',
            name: 'Shadow',
            species: 'cat',
            breed: 'Domestic Shorthair',
            age: 6,
            notes: 'Very independent, prefers to observe from a distance before approaching',
            imageUrl: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 'user_3',
            name: 'Rocky',
            species: 'dog',
            breed: 'Mixed Breed',
            age: 8,
            notes: 'Senior dog who loves gentle walks and afternoon naps in the sun',
            imageUrl: 'https://example.com/pet-photos/rocky-mixed-breed.jpg',
            createdAt: new Date('2023-10-18').toISOString(),
            updatedAt: new Date('2023-10-18').toISOString(),
        },
        {
            userId: 'user_3',
            name: 'Sunny',
            species: 'bird',
            breed: 'Canary',
            age: 1,
            notes: 'Beautiful singer, especially active in the mornings',
            imageUrl: 'https://example.com/pet-photos/sunny-canary.jpg',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            userId: 'user_3',
            name: 'Slither',
            species: 'reptile',
            breed: 'Ball Python',
            age: 4,
            notes: 'Very docile, feed frozen mice monthly, maintain humidity at 60%',
            imageUrl: 'https://example.com/pet-photos/slither-ball-python.jpg',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: 'user_2',
            name: 'Guppy',
            species: 'fish',
            breed: 'Guppy',
            age: null,
            notes: 'Fast swimmers, keep in groups of 5 or more for best behavior',
            imageUrl: 'https://example.com/pet-photos/guppy-fish.jpg',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        }
    ];

    await db.insert(pets).values(samplePets);
    
    console.log('✅ Pets seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});